version: "3.3"

services:
  ldap-service:
    image: odk/openldap
    restart: always
    volumes:
      - ldap-vol:/var/lib/ldap
      - ldap-slapd.d-vol:/etc/ldap/slapd.d
    env_file:
      - ldap.env
    ports:
      - "389:389"

  odk-x-admin:
    build: .
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    env_file:
      - ldap.env

volumes:
  # these 2 need to be removed together
  ldap-vol: # preserve ldap db
  ldap-slapd.d-vol: # preserve ldap settings