version: "3.3"

services:
  ldap-service:
    image: odk/openldap
    deploy:
      replicas: 1
    networks:
      - ldap-network
    volumes:
      - ldap-vol:/var/lib/ldap
      - ldap-slapd.d-vol:/etc/ldap/slapd.d
    env_file:
      - ldap.env

  phpldapadmin:
    image: odk/phpldapadmin
    deploy:
      replicas: 1
    ports:
      - "${PHP_LDAPADMIN_PORT:-40000}:443"
    networks:
      - ldap-network
    env_file:
      - ldap.env

networks:
  ldap-network:
    driver: overlay
    driver_opts:
      encrypted: ""
    internal: true

volumes:
  # these 2 need to be removed together
  ldap-vol: # preserve ldap db
  ldap-slapd.d-vol: # preserve ldap settings